import { NAME } from './consts';

export const FETCH_COLORS = `${NAME}/FETCH_COLORS`;
export const FETCH_COLORS_PENDING = `${NAME}/FETCH_COLORS_PENDING`;
export const FETCH_COLORS_FULFILLED = `${NAME}/FETCH_COLORS_FULFILLED`;
export const FETCH_COLORS_REJECTED = `${NAME}/FETCH_COLORS_REJECTED`;
